[project]
name = "boundaries"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common",
    "scripts"
]

[tool.uv.workspace]
members = ["tasks/*", "common", "scripts"]

[tool.uv.sources]
common = { workspace = true }
scripts = { workspace = true }

[tool.ruff.lint]
select = ["I"]

[dependency-groups]
dev = [
    "ruff>=0.16.0",
]
