server:
   ip: 127.0.0.1
   port: 8080

tiles:
   - name: admin_boundaries
     src: tmp/processed/admin_boundaries_2025-01-01.versatiles
   - name: admin_labels
     src: tmp/processed/admin_labels_2025-01-01.versatiles

cors:
   allowed_origins:
      - "*"

extra_response_headers:
  Cache-Control: "no-cache"

static:
  - src: ./frontend-dev.tar.gz
