image_repo: europe-west3-docker.pkg.dev/swr-datalab-prod/etl-images-airflow-swr-data-lab

# The metadata for the dag are defined below
dag_metadata:
  description: 'A data pipeline that does awesome things.'
  schedule_interval: '10 * * * *'
  max_active_runs: 1
  catchup: False
  is_paused_upon_creation: False
  start_date: 1 # Given in days

  default_args:
    owner: airflow
    depends_on_past: False
    retries: 1
    retry_delay: 3 # Given in minutes

dataplex_metadata:
  # Manual Dataset Specification
  dataset_id: null # WICHTIG!!!! Bei Scraper-Repos die entsprechende Dataset_id, soll kein Datenkatalog-Eintrag erstellt werden null

  fields:
    quellenname: '' # Sprechender Name der Datenquelle, bspw. Tierseucheninformationssystem (TSIS)
    quelle_kurz: '' # Kurzname der Quelle, der auch als Dataset Präfix genutzt wird, bspw. fli
    urheber: '' # Urheber (Wer stellt die Daten zur Verfügung), bspw. Friedrich Löffler Institut
    beschreibung: '' # Beschreibung der Datenquelle
    url: '' # Link zur Originalquelle (so genau wie möglich)
    datentyp: 'dynamisch' # Airflow Code ist per definition dynamisch, alternativ "statisch"
    datenstand: '' # freilassen: wird über die Big Query Tabellen befüllt
    meldedatum: '' # freilassen: wird über die Big Query Tabellen befüllt
    tags: # Schlüsselwörter die helfen, eine Datenquelle zu finden, bswp. tierseuchen, schweinepest
      - tag1
      - tag2
    anmerkung: '' # Generelle Anmerkungen zur Datenquelle
    data_link: '' # Link zu den Daten außerhalb von Big Query, bspw. Aleph oder Google Buckets

# The parameters for KubernetesPodOperator are defined below.
# The variable image_suffix shall be the same as the name of the folder with
# the source code for extract, transform, load and other tasks.
# Replace the environment variables with your corresponding env variables.
# The variable task_id can be set to a arbitrary string.
# Following vars can be reused by prepending the var name with a *, i.e. *dag_env_vars

dag_env_vars: &dag_env_vars
  airflow_env_var1: "{{ var.value.get('DUMMY_ENV_VAR1') }}"
  env_var2: 'val_env_var1'

container_resource: &container_resource
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 1000Mi

dag_task_parameters:
  - task_id: scrape_x
    image_suffix: python_allrounder
    cmds:
      - python
      - scraper_main.py
    environment_variables:
      <<: *dag_env_vars
      env_var0: 'val_env_var0'
    container_resource:
      <<: *container_resource
    is_delete_operator_pod: False

  - task_id: refine_x
    image_suffix: python_allrounder
    cmds:
      - python
      - refiner_main.py
    environment_variables:
      <<: *dag_env_vars
      env_var0: 'val_env_var0'
    container_resource:
      <<: *container_resource
    is_delete_operator_pod: False
