name: deploy pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**/dag/**"
      - "**/tasks/**"

permissions:
  contents: write
  id-token: write

env:
  DOCKER_BUILDKIT: 1
  REGISTRY_NAME: etl-images-airflow-swr-data-lab
  REGISTRY_REGION: europe-west3
  PROJECT_ID: swr-datalab-prod
  BUCKET_NAME: europe-west3-swr-datalab-ai-4eee14a8-bucket
  GCE_INSTANCE_NAME: datapipelines
  GCE_ZONE: europe-west3-a

jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 #v3.0.0
        id: gcp-auth
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 #v4.4.0
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}
      - name: set dag name
        run: |
          ESCAPED_NAME=$(echo "${{ steps.get-repo-name.outputs.name }}" | tr '-' '_')
          echo "name=$ESCAPED_NAME" >> $GITHUB_OUTPUT
      - name: get dockerfiles
        run: |
          DOCKERFILES=$(find . -name Dockerfile)
          echo "dockerfiles=$(echo $DOCKERFILES | tr '\n' ' ')" >> $GITHUB_OUTPUT
      - name: build and push docker images
        env:
            GAR_READER_SA_KEY: ${{ secrets.GAR_READER_SA_KEY }}
            DOCKERFILES: ${{ steps.get-dockerfiles.outputs.dockerfiles }}
        run: |
          if [[ -z "${{ steps.get-dockerfiles.outputs.dockerfiles }}" ]]; then
            echo "[INFO] No Dockerfiles found."
            exit 0
          fi

          for DOCKERFILE in ${{ steps.get-dockerfiles.outputs.dockerfiles }}; do
            BUILD_CONTEXT_INPUT="${{ inputs.build_context }}"
            if [[ -n "$BUILD_CONTEXT_INPUT" ]]; then
              BUILD_CONTEXT_DIR="$BUILD_CONTEXT_INPUT"
            else
              BUILD_CONTEXT_DIR=$(dirname "$DOCKERFILE")
            fi

            IMAGE_NAME=$(echo "$DOCKERFILE" | sed 's/\/Dockerfile//; s/\//_/g; s/\.//g')

            docker build \
              --file "$DOCKERFILE" \
              --secret id=google_creds,env=GAR_READER_SA_KEY \
              --push \
              --tag "${{ env.REGISTRY_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ steps.set-dag-name.outputs.name }}${IMAGE_NAME}:${{ inputs.image_tag }}" \
              "$BUILD_CONTEXT_DIR"
            echo "Built image: $IMAGE_NAME"
          done
      - name: pull docker image into compute engine
        uses: google-github-actions/ssh-compute@907d824cb3cb1630ddd72c032f8c64be474b4117 #v2.0.0
        with:
          instance_name: ${{ env.GCE_INSTANCE_NAME }}
          zone: ${{ env.GCE_ZONE }}
          project_id: ${{ env.PROJECT_ID }}
          ssh_private_key: ${{ secrets.GCE_DATAPIPELINES_SSH_KEY }}
          command: |
            TOKEN=$(curl -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" | jq -r .access_token)
            docker login -u oauth2accesstoken --password "$TOKEN" https://${{ env.REGISTRY_REGION }}-docker.pkg.dev
            if [[ -z "${{ steps.get-dockerfiles.outputs.dockerfiles }}" ]]; then
              echo "No Dockerfiles found."
            else
              IFS=' '
              for DOCKERFILE in ${{ steps.get-dockerfiles.outputs.dockerfiles }}; do
                IMAGE_NAME=$(echo $DOCKERFILE | sed 's/\/Dockerfile//; s/\//_/g; s/\.//g')
                docker pull ${{ env.REGISTRY_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ steps.set-dag-name.outputs.name }}$IMAGE_NAME:${{ inputs.image_tag }}
              done
            fi
            docker container prune -f
            docker image prune -f

      - name: upload dag/ to gcp
        uses: google-github-actions/upload-cloud-storage@6397bd7208e18d13ba2619ee21b9873edc94427a #v3.0.0
        with:
          path: './dag'
          destination: '${{ env.BUCKET_NAME}}/dags/${{ steps.set-dag-name.outputs.name }}'
          parent: false