name: Build and deploy demo

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'demo/**'
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  reuse-build-and-deploy-node-app:
    uses: SWRData/workflows-swr-data-lab/.github/workflows/build_and_deploy_node_app.yml@main
    with:
      working_directory: 'demo'
      full_repository: ${{ github.repository }}
      branch: ${{ github.head_ref || github.ref_name }}
      install_command: 'npm install -g npm && npm ci'
      build_command: 'npm run build'
      build_path: 'build'
      node_version: 25
    secrets:
      SWR_NPM_TOKEN: ${{ secrets.SWR_NPM_TOKEN }}
