name: ty

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'tasks/make_boundaries/**'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'tasks/make_boundaries/**'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  ty:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tasks/make_boundaries
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable_cache: true
      - name: uv sync
        run: uv sync
      - name: ty check
        run: uvx ty check src
