name: ty

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "tasks/make_boundaries/**"
      - "scripts/**"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "tasks/make_boundaries/**"
      - "scripts/**"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: astral-sh/setup-uv@d7fe1a5a186096cccdd5fa2252d223b54fa53a72
        with:
          enable-cache: true
      - name: uv sync tasks
        working-directory: tasks/make_boundaries
        run: uv sync
      - name: ty check tasks
        working-directory: tasks/make_boundaries
        run: uvx ty check src
      - name: uv sync scripts
        working-directory: scripts
        run: uv sync
      - name: ty check scripts
        working-directory: scripts
        run: uvx ty check
