name: ty

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "tasks/make_boundaries/**"
      - "scripts/**"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "tasks/make_boundaries/**"
      - "scripts/**"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # 8.1.0
        with:
          enable-cache: true
      - name: uv sync tasks
        working-directory: tasks/make_boundaries
        run: uv sync
      - name: ty check tasks
        working-directory: tasks/make_boundaries
        run: uvx ty check src
      - name: uv sync scripts
        working-directory: scripts
        run: uv sync
      - name: ty check scripts
        working-directory: scripts
        run: uvx ty check
